apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../../sample-app-gcptest/docker-compose.yml
    kompose.version: 1.31.2 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: sample-app-front
  name: sample-app-front
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: sample-app-front
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f ../../sample-app-gcptest/docker-compose.yml
        kompose.version: 1.31.2 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.network/sample-app-gcptest-sample-app-network: "true"
        io.kompose.service: sample-app-front
    spec:
      containers:
        - image: asia-northeast1-docker.pkg.dev/paloma-cicd/paloma-cicd-repo-gke/sample-app-front:SHORT_SHA
          name: sample-app-front
          ports:
            - containerPort: 8080
              hostIP: 127.0.0.1
              hostPort: 8080
              protocol: TCP
          envFrom:
            - configMapRef:
                name: sample-app-front-configmap
          resources:
            requests:
              cpu: 50m
              memory: 100Mi
          tty: true
          workingDir: /app
      restartPolicy: Always
      nodeSelector:
        cloud.google.com/gke-nodepool: kh-paloma-m01-01-gke-nodes01
status: {}
